services:
  database:
    image: postgres:latest
    restart: always
    container_name: cybersec-db-phase4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: cybersec-web-phase4
    restart: always
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data: